# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timelog',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='START_TIME')),
                ('end_time', models.DateTimeField(blank=True, db_column='END_TIME', null=True)),
            ],
            options={
                'db_table': 'TIMELOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('card_id', models.IntegerField(db_column='CARD_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=30)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=30)),
                ('class_field', models.CharField(db_column='CLASS', max_length=15)),
                ('is_admin', models.IntegerField(db_column='IS_ADMIN')),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
    ]
