# Generated by Django 2.0 on 2018-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('users', models.ManyToManyField(db_column='USERS', to='logger.User')),
            ],
            options={
                'db_table': 'TEAM',
            },
        ),
    ]
