INSERT INTO USER (CARD_ID, FIRST_NAME, LAST_NAME, IS_ADMIN) VALUES (1111, "Kevin", "Hoogendijk", 1);
INSERT INTO USER (CARD_ID, FIRST_NAME, LAST_NAME, IS_ADMIN) VALUES (2222, "Sebastian", "Norlin", 1);
