CREATE TABLE USER (
  CARD_ID int NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  CLASS VARCHAR(15) NOT NULL,    
  PRIMARY KEY (CARD_ID)
);

CREATE TABLE TIMELOG(
  CARD_ID int NOT NULL,
  START_TIME datetime NOT NULL,
  END_TIME datetime
);
