DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TIMELOG;

CREATE TABLE USER (
  CARD_ID int NOT NULL,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  CLASS VARCHAR(15) NOT NULL,    
  IS_ADMIN BOOL NOT NULL,
  PRIMARY KEY (CARD_ID)
);

CREATE TABLE TIMELOG(
  ID BIGINT NOT NULL AUTO_INCREMENT,
  CARD_ID int NOT NULL,
  START_TIME datetime NOT NULL,
  END_TIME datetime,
  PRIMARY KEY(ID)
);
